site_name: Full-stack technology space
site_url: https://github.com/Kooooooma/komas-blog

repo_url: https://github.com/Kooooooma/komas-blog

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.footer
  palette: 
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: 深色模式
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: 浅色模式

markdown_extensions:
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Kooooooma/komas-blog
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_Kooooooma
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/koma-zhang-6058a92a6/
  generator: false

copyright: Copyright &copy; 2023 - 3023 Koma
